/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GhostRouteImport } from './routes/ghost'
import { Route as TradesmateRouteImport } from './routes/tradesmate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostRoute = GhostRouteImport.update({
  id: '/ghost',
  path: '/ghost',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesmateRoute = TradesmateRouteImport.update({
  id: '/tradesmate',
  path: '/tradesmate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ghost': typeof GhostRoute
  '/tradesmate': typeof TradesmateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ghost': typeof GhostRoute
  '/tradesmate': typeof TradesmateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ghost': typeof GhostRoute
  '/tradesmate': typeof TradesmateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/ghost' | '/tradesmate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/ghost' | '/tradesmate'
  id: '__root__' | '/' | '/contact' | '/ghost' | '/tradesmate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GhostRoute: typeof GhostRoute
  TradesmateRoute: typeof TradesmateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghost': {
      id: '/ghost'
      path: '/ghost'
      fullPath: '/ghost'
      preLoaderRoute: typeof GhostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tradesmate': {
      id: '/tradesmate'
      path: '/tradesmate'
      fullPath: '/tradesmate'
      preLoaderRoute: typeof TradesmateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GhostRoute: GhostRoute,
  TradesmateRoute: TradesmateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
